version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
    reviewers:
      - Fouppy
    labels:
      - type:dependencies
      - dependencies
      - dependabot
    assignees:
      - Fouppy
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
