name: Log new release

# on: release

on:
  workflow_run:
    workflows: ["Publish release"]
    types:
      - completed

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - name: Send logs to LogFlare
        uses: logflare/action@v1
        id: stats
        with:
          api_key: ${{ secrets.LOGFLARE_API_KEY }}
          source_id: ${{ secrets.LOGFLARE_SOURCE_ID }}
          message: "new release: ${{ github.event.release.html_url }}"
          metadata: |
            {
              "version": "${{ github.event.release.tag_name }}"
            }
