name: Log new release

on: release

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - uses: logflare/action@v1
        id: stats
        with:
          api_key: ${{ secrets.LOGFLARE_API_KEY }}
          source_id: ${{ secrets.LOGFLARE_SOURCE_ID }}
          message: "new release: ${{ github.event.release.html_url }}"
          metadata: |
            {
              "version": "${{ github.event.release.tag_name }}"
            }
